[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = """
php -m
php artisan migrate --force
php artisan serve --host=0.0.0.0 --port=$PORT
"""